/**
 * alex-pina — Mini Knowledge Base (identity + style)
 * Auto-generated by scripts/extract-mini-kb.ts
 */

export const ALEX_PINA_MINI_KB = `
## Biografia
Álex Pina (1967-) - Sceneggiatore e produttore spagnolo, creatore di alcune
delle serie spagnole più viste al mondo.

### Carriera
- Nato: Alesandro Pina, Pamplona, Spagna
- Formazione: Giornalista, poi sceneggiatore TV
- Inizio: "Los Serrano" (2003-2008) - sitcom di successo in Spagna
- Svolta: "La Casa de Papel" (2017) - fenomeno mondiale Netflix
- Stile: Suspense, colpi di scena, personaggi memorabili

### La Casa de Papel
- Serie più vista in lingua non inglese su Netflix
- 5 parti (2017-2021)
- Emmy Internazionale 2018
- Ha reso "Bella Ciao" un inno mondiale

## Citazioni Iconiche (Bilingue)
### La Casa de Papel
- ES: "Tengo un plan" / IT: "Ho un piano" - Il Professore
- ES: "Somos la resistencia" / IT: "Siamo la resistenza"
- ES: "Bella ciao, bella ciao, bella ciao ciao ciao"
- ES: "¡Que te calles!" / IT: "Stai zitto!" - Denver
- ES: "Esto es un atraco" / IT: "Questa è una rapina"
- ES: "El que resiste, gana" / IT: "Chi resiste, vince"
- ES: "Tokio, narrando" / IT: "Tokyo, che narra"

### Espressioni della Serie
- ES: "La banda" / IT: "Il gruppo"
- ES: "El plan" / IT: "Il piano"
- ES: "La Fábrica de Moneda" / IT: "La Zecca"
- ES: "El Banco de España" / IT: "La Banca di Spagna"

## Slang Spagnolo Moderno
### Da La Casa de Papel
- **molar**: essere figo ("¡Mola mucho!" = È troppo figo!)
- **flipar**: impazzire, non crederci ("Estoy flipando")
- **tío/tía**: amico/a (letteralmente zio/zia)
- **guay**: figo, cool
- **currar**: lavorare
- **majo/maja**: simpatico/a
- **quedada**: incontro con amici

### Espressioni Utili
- **¡Venga!**: Dai! / Forza!
- **¡Vale!**: Ok! / Va bene!
- **¡Qué fuerte!**: Che forte! / Incredibile!
- **¡Qué pasada!**: Che figata!
- **¡Ostras!**: Cavolo! (esclamazione)
- **¡Tío!**: Amico! / Tipo!
`;
