/**
 * amici-miei — Mini Knowledge Base (identity + style)
 * Auto-generated by scripts/extract-mini-kb.ts
 */

export const AMICI_MIEI_MINI_KB = `
## I Cinque Amici
1. **Conte Raffaello "Lello" Mascetti** (Ugo Tognazzi)
   - Nobile decaduto, vive in uno scantinato in "condizioni di estrema indigenza"
   - Mantenuto dagli amici ma con dignita
   - Creatore delle supercazzole - l'arte di confondere con elegante nonsenso
   - Moglie: Alice (Milena Vukotic) - santa donna che sopporta tutto
   - Amante: Titti (Silvia Dionisio) - studentessa 18enne, figlia di un colonnello
   - In Atto II: colpito da ictus, finisce su sedia a rotelle
   - In Atto III: paralizzato ma recupera la parola, dopo la morte di Alice

2. **Giorgio Perozzi** (Philippe Noiret)
   - Giornalista, voce narrante del primo film
   - Moglie "tremenda", figlio serioso che non lo capisce
   - Molte avventure extraconiugali
   - MUORE alla fine del primo film (infarto)
   - Ultima battuta: una supercazzola al prete per l'estrema unzione
   - Appare in Atto II solo nei flashback

3. **Rambaldo Melandri** (Gastone Moschin)
   - Architetto impiegato al comune
   - Si innamora facilmente, cerca disperatamente l'amore
   - Disposto ad abbandonare gli amici per una donna
   - In Atto II: si converte al cattolicesimo per una donna devota
   - In Atto III: si fa ricoverare nella casa di riposo per stare col Mascetti

4. **Guido Necchi** (Duilio Del Prete nel I, Renzo Montagnani nel II e III)
   - Proprietario del bar-ristorante, quartier generale del gruppo
   - Considerato "l'anima geniale del gruppo"
   - Sposato con Carmen
   - In Atto II: scopre l'infedelta di Carmen e si vendica dell'amante

5. **Professor Alfeo Sassaroli** (Adolfo Celi)
   - Chirurgo brillante, primario ospedaliero con clinica a Pescia
   - Annoiato dalla "psicopatica moglie" Donatella
   - Unico entrato nel gruppo in eta adulta (li conosce dopo un incidente stradale)
   - Quando Melandri si innamora di sua moglie in clinica, gliela "cede" con cinismo
   - In Atto III: vende la clinica e compra la casa di riposo

## La Supercazzola
Frase priva di senso, esposta con sicurezza per confondere l'interlocutore.
Entrata nel vocabolario Zingarelli nel 2015.

### Vocabolario
- **Antani** - parola simbolo del nonsenso
- **Tarapia tapioco** - espressione inventata
- **Scappellamento a destra/sinistra** - termine tecnico fasullo
- **Come se fosse** - connettivo tipico
- **Prematurata/o** - aggettivo inventato
- **Brematurata** - variante
- **Per due** - chiusura tipica
`;
