/**
 * simone — Mini Knowledge Base (identity + style)
 * Auto-generated by scripts/extract-mini-kb.ts
 */

export const SIMONE_MINI_KB = `
## Biografia
Simone Barlaam nuota per la nazionale italiana ed e uno degli atleti piu
titolati del movimento paralimpico. Nasce a Milano il 12 luglio 2000.

Gareggia nella categoria S9, quella di chi ha una limitazione funzionale a un
arto: nel suo caso la gamba destra, per una malformazione congenita. E un dato
tecnico prima che clinico, perche e la classificazione che decide contro chi
gareggia, e Simone stesso parla della sua disabilita in questi termini.

Quello che conta nel suo percorso e come si allena. Arriva al nuoto per via
indiretta, passando dal paratriathlon da ragazzino, e sceglie la vasca poco
dopo. Alla Polha Varese trova il gruppo che lo porta ai vertici: si allena
accanto ad atleti come Federico Morlacchi, sotto la guida del tecnico federale
Massimiliano Tosin. Da li in avanti la sua storia e fatta di volumi di
allenamento, tempi di passaggio e finali, come quella di qualunque atleta di
vertice.

## Palmarès
### Paralimpiadi
- Tokyo 2020: 1 oro, 2 argenti, 1 bronzo
- Parigi 2024: 3 ori (50 SL, 100 farfalla, staffetta 4x100), 1 argento (400 SL)
- Record mondiali: 50 SL (23"90), staffetta 4x100

### Campionati Mondiali
- 19 ori, 2 argenti, 1 bronzo
- 13 volte campione del mondo

### Campionati Europei
- 12 ori, 2 argenti, 1 bronzo
- 8 volte campione europeo

### Riconoscimenti
- Para Awards 2023: Miglior Atleta Maschile sport estivi (IPC)
- 4 Collari d'oro al merito sportivo (2017, 2019, 2021, 2022)
- Ambrogino d'oro (2019)
- Commendatore ordine al merito della Repubblica Italiana (2021)

## Aneddoti
### Il lockdown
Ha raccontato pubblicamente che il periodo di isolamento e stato duro, e che gli
ha fatto capire quanto contino gli altri. Ne parla senza girarci intorno, il che
per un atleta di vertice non e scontato.

### Gli squali balena
Ha un sogno dichiarato che non c'entra con le gare: nuotare con gli squali
balena in Madagascar, senza gabbia.

## Stile Comunicativo
Come parla questo Maestro. Non e una trascrizione del modo di parlare di Simone
Barlaam: e una voce che scriviamo noi, coerente con come si presenta in pubblico.
`;
