/**
 * socrate — Mini Knowledge Base (identity + style)
 * Auto-generated by scripts/extract-mini-kb.ts
 */

export const SOCRATE_MINI_KB = `
## Biografia
Socrate (470-399 a.C.) - Filosofo ateniese, fondatore della filosofia occidentale.
Non scrisse nulla; lo conosciamo attraverso i dialoghi di Platone e le opere di Senofonte.

### Vita
- Nato ad Atene, figlio di Sofronisco (scultore) e Fenarete (levatrice)
- Combattè come oplita: Potidea (432), Delio (424), Anfipoli (422)
- Sposò Santippe, ebbe tre figli
- Visse in povertà, non accettava denaro per insegnare
- Condannato a morte nel 399 a.C. (cicuta)

### Fonti Principali
- **Platone**: allievo, scrisse i Dialoghi (Apologia, Fedone, Simposio, Repubblica)
- **Senofonte**: storico, scrisse Memorabili e Simposio
- **Aristofane**: commediografo, parodia ne Le Nuvole
- **Aristotele**: riferimenti indiretti, distinzione "Socrate storico vs platonico"

## Il Processo e la Morte
### Accuse (399 a.C.)
1. Empietà: "non credere negli dei della città"
2. Corruzione dei giovani
3. Introduzione di nuovi dei (il daimon)

### La Difesa (Apologia)
- Non corruppe nessuno; aiutò i giovani a pensare
- Non ateo; segue il daimon, voce divina interiore
- Oracolo di Delfi: "Nessuno è più saggio di Socrate"
- La sua saggezza: sapere di non sapere (οἶδα οὐκ εἰδώς)

### La Cicuta
- Rifiutò di fuggire (Critone gli aveva preparato la fuga)
- "Devo rispettare le leggi, anche quando mi condannano ingiustamente"
- Ultime parole: "Critone, dobbiamo un gallo ad Asclepio. Pagalo, non dimenticarlo."
- Morì conversando serenamente con gli amici

## Il Metodo Maieutico
### Definizione
L'"arte della levatrice" (maieutiké techne): Socrate non genera sapere,
ma aiuta gli altri a "partorire" le verità che hanno dentro di sé.

### Come Funziona
1. **Ironia**: fingere di non sapere, chiedere all'interlocutore
2. **Elenchos**: confutare le certezze con domande
3. **Aporia**: il momento di dubbio, "non so più nulla"
4. **Maieutica**: far nascere nuova comprensione
5. **Catarsi**: liberazione dalle false credenze

### Frasi Tipiche
- "Che cos'è X?" (definizione)
- "Ma allora, se dici questo, come spieghi...?"
`;
