#!/bin/bash

# Remaining files to split
# This script documents the files that still need to be split and their strategy

echo "Remaining files to split:"
echo ""
echo "1. src/lib/safety/output-sanitizer.ts (347 lines)"
echo "   Strategy: Split into output-sanitizer-patterns.ts and output-sanitizer-core.ts"
echo ""
echo "2. src/lib/safety/age-gating.ts (378 lines)"
echo "   Strategy: Split into age-gating-matrix.ts and age-gating-core.ts"
echo ""
echo "3. src/lib/storage/materials-db.ts (397 lines)"
echo "   Strategy: Split into materials-db-crud.ts, materials-db-schema.ts, materials-db-thumbnail.ts"
echo ""
echo "4. src/lib/storage/local-provider.ts (348 lines)"
echo "   Strategy: Keep as one file (class-based structure is tight)"
echo ""
echo "5. src/lib/tools/tool-persistence.ts (374 lines)"
echo "   Strategy: Split into tool-persistence-crud.ts and tool-persistence-utils.ts"
echo ""
echo "6. src/lib/tools/handlers/study-kit-handler.ts (372 lines)"
echo "   Strategy: Split into study-kit-extraction.ts and study-kit-generators.ts"
echo ""
echo "7. src/lib/pdf-generator/utils/content-extractor.ts (385 lines)"
echo "   Strategy: Split into content-extractor-core.ts and content-extractor-parsers.ts"
echo ""
echo "8. src/lib/education/adaptive-quiz.ts (384 lines)"
echo "   Strategy: Split into adaptive-quiz-analysis.ts and adaptive-quiz-suggestions.ts"
echo ""
echo "9. src/lib/profile/types.ts (347 lines)"
echo "   Strategy: Keep as single file (mostly type definitions)"
echo ""
echo "10. src/lib/method-progress/types.ts (337 lines)"
echo "    Strategy: Keep as single file (mostly type definitions)"
echo ""
echo "11. src/lib/rag/semantic-chunker.ts (333 lines)"
echo "    Strategy: Keep as single file (functions are well-organized)"
echo ""
echo "12. src/types/tools/tool-schemas.ts (366 lines)"
echo "    Strategy: Keep as single file (tool definitions are related)"
echo ""

echo ""
echo "After creating all splits:"
echo "1. Update all imports that reference the old files"
echo "2. Delete the original oversized files"
echo "3. Run: npm run typecheck"
echo "4. Run: npm run lint"
echo "5. Run: npm run build"
