// Character data and color configuration for character-settings component

export const BORDER_COLORS = [
  { name: "Rosa", value: "#EC4899" },
  { name: "Blu", value: "#3B82F6" },
  { name: "Verde", value: "#10B981" },
  { name: "Viola", value: "#8B5CF6" },
  { name: "Arancione", value: "#F97316" },
  { name: "Rosso", value: "#EF4444" },
  { name: "Ambra", value: "#F59E0B" },
  { name: "Indaco", value: "#6366F1" },
  { name: "Ciano", value: "#06B6D4" },
  { name: "Lime", value: "#84CC16" },
];

export const COACHES = [
  {
    id: "melissa" as const,
    name: "Melissa",
    avatar: "/avatars/melissa.jpg",
    description: "Giovane, intelligente, allegra, paziente, entusiasta",
    tagline: "Entusiasta e positiva",
    color: "from-pink-500 to-rose-500",
    bgColor: "bg-pink-50 dark:bg-pink-900/20",
    borderColor: "border-pink-200 dark:border-pink-800",
    activeBorder: "border-pink-500 ring-2 ring-pink-500/50",
  },
  {
    id: "roberto" as const,
    name: "Roberto",
    avatar: "/avatars/roberto.webp",
    description: "Giovane, calmo, rassicurante, paziente, affidabile",
    tagline: "Calmo e rassicurante",
    color: "from-blue-500 to-indigo-500",
    bgColor: "bg-blue-50 dark:bg-blue-900/20",
    borderColor: "border-blue-200 dark:border-blue-800",
    activeBorder: "border-blue-500 ring-2 ring-blue-500/50",
  },
  {
    id: "chiara" as const,
    name: "Chiara",
    avatar: "/avatars/chiara.webp",
    description: "Organizzata, metodica, fresca di studi, empatica",
    tagline: "Appena laureata, ti capisce",
    color: "from-violet-500 to-purple-500",
    bgColor: "bg-violet-50 dark:bg-violet-900/20",
    borderColor: "border-violet-200 dark:border-violet-800",
    activeBorder: "border-violet-500 ring-2 ring-violet-500/50",
  },
  {
    id: "andrea" as const,
    name: "Andrea",
    avatar: "/avatars/andrea.webp",
    description: "Sportiva, energica, pratica, motivazionale",
    tagline: "Energia e pause attive",
    color: "from-orange-500 to-amber-500",
    bgColor: "bg-orange-50 dark:bg-orange-900/20",
    borderColor: "border-orange-200 dark:border-orange-800",
    activeBorder: "border-orange-500 ring-2 ring-orange-500/50",
  },
  {
    id: "favij" as const,
    name: "Favij",
    avatar: "/avatars/favij.jpg",
    description: "Gamer, rilassato, simpatico, creativo, tech-savvy",
    tagline: "Lo studio come un gioco",
    color: "from-red-500 to-rose-500",
    bgColor: "bg-red-50 dark:bg-red-900/20",
    borderColor: "border-red-200 dark:border-red-800",
    activeBorder: "border-red-500 ring-2 ring-red-500/50",
  },
  {
    id: "laura" as const,
    name: "Laura",
    avatar: "/avatars/laura.webp",
    description: "Riflessiva, calma, empatica, paziente, accogliente",
    tagline: "Calma e riflessiva",
    color: "from-emerald-500 to-green-500",
    bgColor: "bg-emerald-50 dark:bg-emerald-900/20",
    borderColor: "border-emerald-200 dark:border-emerald-800",
    activeBorder: "border-emerald-500 ring-2 ring-emerald-500/50",
  },
];

export const BUDDIES = [
  {
    id: "mario" as const,
    name: "Mario",
    avatar: "/avatars/mario.jpg",
    description: "Amichevole, ironico, comprensivo, alla mano",
    tagline: "Il tuo amico che ti capisce",
    color: "from-emerald-500 to-teal-500",
    bgColor: "bg-emerald-50 dark:bg-emerald-900/20",
    borderColor: "border-emerald-200 dark:border-emerald-800",
    activeBorder: "border-emerald-500 ring-2 ring-emerald-500/50",
  },
  {
    id: "noemi" as const,
    name: "Noemi",
    avatar: "/avatars/noemi.webp",
    description: "Empatica, solare, accogliente, buona ascoltatrice",
    tagline: "La tua amica che ti ascolta",
    color: "from-purple-500 to-violet-500",
    bgColor: "bg-purple-50 dark:bg-purple-900/20",
    borderColor: "border-purple-200 dark:border-purple-800",
    activeBorder: "border-purple-500 ring-2 ring-purple-500/50",
  },
  {
    id: "enea" as const,
    name: "Enea",
    avatar: "/avatars/enea.webp",
    description: "Allegro, positivo, spiritoso, energico",
    tagline: "Ti tira su il morale",
    color: "from-amber-500 to-yellow-500",
    bgColor: "bg-amber-50 dark:bg-amber-900/20",
    borderColor: "border-amber-200 dark:border-amber-800",
    activeBorder: "border-amber-500 ring-2 ring-amber-500/50",
  },
  {
    id: "bruno" as const,
    name: "Bruno",
    avatar: "/avatars/bruno.webp",
    description: "Riflessivo, calmo, profondo, buon ascoltatore",
    tagline: "Ti ascolta davvero",
    color: "from-indigo-500 to-blue-500",
    bgColor: "bg-indigo-50 dark:bg-indigo-900/20",
    borderColor: "border-indigo-200 dark:border-indigo-800",
    activeBorder: "border-indigo-500 ring-2 ring-indigo-500/50",
  },
  {
    id: "sofia" as const,
    name: "Sofia",
    avatar: "/avatars/sofia.webp",
    description: "Creativa, sognatrice, profonda, artistica",
    tagline: "Vede le cose diversamente",
    color: "from-pink-500 to-fuchsia-500",
    bgColor: "bg-pink-50 dark:bg-pink-900/20",
    borderColor: "border-pink-200 dark:border-pink-800",
    activeBorder: "border-pink-500 ring-2 ring-pink-500/50",
  },
  {
    id: "marta" as const,
    name: "Marta",
    avatar: "/avatars/marta.webp",
    description: "Sportiva, determinata, pratica, diretta ma gentile",
    tagline: "Determinata e sportiva",
    color: "from-sky-500 to-cyan-500",
    bgColor: "bg-sky-50 dark:bg-sky-900/20",
    borderColor: "border-sky-200 dark:border-sky-800",
    activeBorder: "border-sky-500 ring-2 ring-sky-500/50",
  },
];
