"""Generated web safety constants; regenerate with tests/transcript_safety_generate.mjs.
Do not edit patterns by hand. JavaScript source and flags are retained verbatim.
"""

PROFANITY_IT = (
    ["\\bc[a4@]zz[o0]","gi"],
    ["\\bm[i1]nch[i1][a4@]","gi"],
    ["\\bstr[o0]nz[o0a@]","gi"],
    ["\\bv[a4@]ff[a4@]ncul[o0]","gi"],
    ["\\bp[o0]rc[o0a@]\\s*[dp]","gi"],
    ["\\bf[i1]g[a4@]\\s*d[i1]","gi"],
    ["\\bf[o0]tt[i1e3]","gi"],
    ["\\bp[u]tt[a4@]n[a4@]","gi"],
    ["\\bc[o0]gl[i1][o0]n[e3i1]","gi"],
    ["\\btr[o0][i1][a4@]","gi"],
    ["\\bz[o0]ccol[a4@]","gi"],
    ["\\bm[e3]rd[a4@]","gi"],
)

PROFANITY_EN = (
    ["\\bf+u+c+k+","gi"],
    ["\\bs+h+[i1]+t+","gi"],
    ["\\bb+[i1]+t+c+h+","gi"],
    ["\\ba+s+s+h+[o0]+l+e+","gi"],
    ["\\bc+u+n+t+","gi"],
    ["\\bd+[i1]+c+k+","gi"],
    ["\\bp+u+s+s+y+","gi"],
    ["\\bc+[o0]+c+k+","gi"],
    ["\\bn+[i1]+g+g+","gi"],
    ["\\bf+a+g+g*[o0]*t*","gi"],
)

JAILBREAK_PATTERNS = (
    ["ignora\\s+.{0,20}istruzioni","gi"],
    ["ignore\\s+.{0,20}instructions","gi"],
    ["dimentica\\s+.{0,20}regole","gi"],
    ["forget\\s+.{0,20}rules","gi"],
    ["forget\\s+everything","gi"],
    ["system\\s*prompt","gi"],
    ["mostrami\\s+(il\\s+)?prompt","gi"],
    ["show\\s+me\\s+(your\\s+)?prompt","gi"],
    ["what\\s+are\\s+your\\s+instructions","gi"],
    ["fai\\s+finta\\s+di\\s+(essere|non)","gi"],
    ["pretend\\s+(to\\s+be|you\\s+are)","gi"],
    ["you\\s+are\\s+now","gi"],
    ["sei\\s+ora","gi"],
    ["act\\s+as\\s+(if|an?)","gi"],
    ["\\bdan\\s+mode","gi"],
    ["\\bdo\\s+anything\\s+now","gi"],
    ["senza\\s+restrizioni","gi"],
    ["no\\s+restrictions","gi"],
    ["unrestricted\\s+mode","gi"],
    ["developer\\s+mode","gi"],
    ["modo\\s+sviluppatore","gi"],
    ["\\[debug\\]","gi"],
    ["\\[admin\\]","gi"],
    ["continua\\s+la\\s+storia","gi"],
    ["continue\\s+the\\s+story","gi"],
    ["in\\s+the\\s+next\\s+message","gi"],
)

EXPLICIT_PATTERNS = (
    ["\\bsess[o0u]","gi"],
    ["\\bs[e3]x","gi"],
    ["\\bp[o0]rn","gi"],
    ["\\bn[u]d[o0i]","gi"],
    ["\\bnaked","gi"],
    ["\\berotic","gi"],
    ["\\bfeticis","gi"],
    ["\\bbdsm","gi"],
    ["\\bhentai","gi"],
)

VIOLENCE_PATTERNS = (
    ["come\\s+uccidere","gi"],
    ["come\\s+fare\\s+(una\\s+)?bomba","gi"],
    ["costruire\\s+.{0,15}bomba","gi"],
    ["bomba\\s+artigianale","gi"],
    ["come\\s+procurarsi\\s+(un[a']?\\s+)?arm[ai]","gi"],
    ["fabbricare\\s+.{0,10}(arma|esplosiv)","gi"],
    ["voglio\\s+far\\s+del\\s+male","gi"],
    ["how\\s+to\\s+kill","gi"],
    ["how\\s+to\\s+make\\s+(a\\s+)?bomb","gi"],
    ["how\\s+to\\s+get\\s+(a\\s+)?gun","gi"],
    ["where\\s+to\\s+buy\\s+(a\\s+)?weapon","gi"],
    ["want\\s+to\\s+hurt","gi"],
    ["comment\\s+(tuer|fabriquer\\s+(une\\s+)?bombe|se\\s+procurer\\s+(une\\s+)?arme)","gi"],
    ["wie\\s+(man\\s+)?(tötet|eine\\s+bombe\\s+baut|waffe\\s+bekommt)","gi"],
    ["cómo\\s+(matar|hacer\\s+(una\\s+)?bomba|conseguir\\s+(un\\s+)?arma)","gi"],
)

HACKING_PATTERNS = (
    ["hackerare","gi"],
    ["bucare\\s+.{0,15}(rete|sistema|sito)","gi"],
    ["violare\\s+.{0,15}(sistema|rete|account)","gi"],
    ["rubare\\s+.{0,15}password","gi"],
    ["craccare","gi"],
    ["how\\s+to\\s+hack","gi"],
    ["break\\s+into\\s+.{0,15}(system|network|account)","gi"],
    ["steal\\s+.{0,10}password","gi"],
    ["bypass\\s+.{0,10}security","gi"],
    ["pirater\\s+.{0,15}(système|réseau|compte)","gi"],
    ["voler\\s+.{0,10}mot\\s+de\\s+passe","gi"],
    ["hacken\\s+.{0,15}(system|netzwerk|konto)","gi"],
    ["passwort\\s+.{0,10}(stehlen|knacken)","gi"],
    ["hackear\\s+.{0,15}(sistema|red|cuenta)","gi"],
    ["robar\\s+.{0,10}contraseña","gi"],
)

PII_PATTERNS = (
    ["via\\s+[a-z]+\\s+\\d+","gi"],
    ["piazza\\s+[a-z]+\\s+\\d*","gi"],
    ["\\+39\\s*\\d{10}","g"],
    ["\\b3\\d{2}[\\s.-]?\\d{3}[\\s.-]?\\d{4}\\b","g"],
    ["\\b0\\d{1,3}[\\s.-]?\\d{6,8}\\b","g"],
    ["[a-z0-9._%+-]+@[a-z0-9.-]+\\.[a-z]{2,}","gi"],
)

CRISIS_PATTERNS = (
    ["voglio\\s+morire",""],
    ["non\\s+voglio\\s+\\S*\\s*vivere",""],
    ["non\\s+ce\\s+la\\s+faccio\\s+più",""],
    ["\\bmi\\s+faccio\\s+del\\s+male",""],
    ["farmi\\s+del\\s+male",""],
    ["suicidio",""],
    ["ammazzarmi",""],
    ["voglio\\s+ammazzar",""],
    ["tagliarm",""],
    ["nessuno\\s+mi\\s+(vuole|ama)",""],
    ["sarebbe\\s+meglio\\s+se\\s+non\\s+(esistessi|ci\\s+fossi)",""],
    ["meglio\\s+se\\s+non\\s+ci\\s+fossi",""],
    ["mi\\s+odio",""],
    ["mi\\s+faccio\\s+schifo",""],
    ["voglio\\s+sparire",""],
    ["voglio\\s+farla\\s+finita",""],
    ["i\\s+want\\s+to\\s+die",""],
    ["don'?t\\s+want\\s+to\\s+\\S*\\s*live",""],
    ["i\\s+can'?t\\s+take\\s+it\\s+anymore",""],
    ["hurt(ing)?\\s+myself",""],
    ["kill\\s+myself",""],
    ["self[- ]?harm",""],
    ["cutting\\s+myself",""],
    ["nobody\\s+(loves|cares|wants)\\s+me",""],
    ["better\\s+off\\s+(dead|without\\s+me)",""],
    ["i\\s+hate\\s+myself",""],
    ["want\\s+to\\s+disappear",""],
    ["end\\s+it\\s+all",""],
    ["je\\s+veux\\s+mourir",""],
    ["ne\\s+veux\\s+plus\\s+vivre",""],
    ["me\\s+faire\\s+du\\s+mal",""],
    ["me\\s+suicider",""],
    ["en\\s+finir",""],
    ["personne\\s+ne\\s+m'aime",""],
    ["ich\\s+will\\s+sterben",""],
    ["will\\s+nicht\\s+mehr\\s+leben",""],
    ["mich\\s+selbst\\s+verletzen",""],
    ["selbstmord",""],
    ["niemand\\s+(mag|liebt)\\s+mich",""],
    ["mir\\s+selbst\\s+wehtun",""],
    ["quiero\\s+morir(me)?",""],
    ["no\\s+quiero\\s+\\S*\\s*vivir",""],
    ["hacerme\\s+daño",""],
    ["suicid(io|arme)",""],
    ["nadie\\s+me\\s+quiere",""],
    ["mejor\\s+si\\s+no\\s+existiera",""],
)

SEVERE = (
    "suicid",
    "ammazzar",
    "tagliar",
    "farmi del male",
    "voglio morire",
    "non voglio vivere",
    "uccidere",
    "ammazzare",
    "sparare",
    "accoltellare",
    "coca",
    "eroina",
    "mdma",
    "ecstasy",
    "fumare erba",
)
