import type { FeatureFlag, KnownFeatureFlag } from './types';

export const DEFAULT_FLAGS: Record<KnownFeatureFlag, Omit<FeatureFlag, 'id' | 'updatedAt'>> = {
  voice_realtime: {
    name: 'Real-time Voice',
    description: 'WebSocket-based real-time voice conversations',
    status: 'enabled',
    enabledPercentage: 100,
    killSwitch: false,
  },
  voice_realtime_15: {
    name: 'Real-time Voice 1.5',
    description: 'Control rollout of GPT Audio 1.5 realtime stack',
    status: 'enabled',
    enabledPercentage: 100,
    killSwitch: false,
  },
  voice_realtime_2: {
    name: 'Real-time Voice 2.0 (Preview)',
    description:
      'ADR 0165: Drop-in next-gen gpt-realtime-2 (Preview, 2026-05-06). Activated 100% — preferred over v1.5 when AZURE_OPENAI_REALTIME_DEPLOYMENT_V2 is configured (with graceful fallback to V15/legacy).',
    status: 'enabled',
    enabledPercentage: 100,
    killSwitch: false,
  },
  voice_realtime_21: {
    name: 'Real-time Voice 2.1',
    description:
      'ADR 0169: gpt-realtime-2.1 (2026-07-07) + Cedar voice. Better alphanumeric speech (dates/numbers/formulas), noise robustness, lower latency. Preferred over v2 when AZURE_OPENAI_REALTIME_DEPLOYMENT_V21 is set (graceful fallback to V2/V15/legacy).',
    status: 'enabled',
    enabledPercentage: 100,
    killSwitch: false,
  },
  voice_realtime_whisper_transcription: {
    name: 'Realtime Whisper Transcription',
    description:
      'ADR 0165: Use gpt-realtime-whisper as input.transcription.model — tighter caption deltas for DSA profiles.',
    status: 'enabled',
    enabledPercentage: 100,
    killSwitch: false,
  },
  voice_realtime_translate: {
    name: 'Realtime Translate (Pending Azure)',
    description:
      'ADR 0165: gpt-realtime-translate S2S. Deployment exists, but Azure /v1/realtime/translations endpoint is not yet available in swedencentral.',
    status: 'degraded',
    enabledPercentage: 0,
    killSwitch: false,
  },
  rag_enabled: {
    name: 'RAG Retrieval',
    description: 'Semantic search for conversation context',
    status: 'enabled',
    enabledPercentage: 100,
    killSwitch: false,
  },
  flashcards: {
    name: 'FSRS Flashcards',
    description: 'Spaced repetition flashcard system',
    status: 'enabled',
    enabledPercentage: 100,
    killSwitch: false,
  },
  mindmap: {
    name: 'Mind Maps',
    description: 'Interactive mind map generation',
    status: 'enabled',
    enabledPercentage: 100,
    killSwitch: false,
  },
  quiz: {
    name: 'Quiz Generation',
    description: 'AI-generated quizzes from content',
    status: 'enabled',
    enabledPercentage: 100,
    killSwitch: false,
  },
  pomodoro: {
    name: 'Pomodoro Timer',
    description: 'Focus timer with breaks',
    status: 'enabled',
    enabledPercentage: 100,
    killSwitch: false,
  },
  gamification: {
    name: 'Gamification',
    description: 'XP, levels, and achievements',
    status: 'enabled',
    enabledPercentage: 100,
    killSwitch: false,
  },
  parent_dashboard: {
    name: 'Parent Dashboard',
    description: 'Parent/professor monitoring portal',
    status: 'enabled',
    enabledPercentage: 100,
    killSwitch: false,
  },
  pdf_export: {
    name: 'PDF Export',
    description: 'Accessible PDF generation',
    status: 'enabled',
    enabledPercentage: 100,
    killSwitch: false,
  },
  ambient_audio: {
    name: 'Ambient Audio',
    description: 'Background study sounds',
    status: 'enabled',
    enabledPercentage: 100,
    killSwitch: false,
  },
  voice_ga_protocol: {
    name: 'Voice GA Protocol',
    description: 'Use GA realtime API (session.type=realtime format)',
    status: 'enabled',
    enabledPercentage: 100,
    killSwitch: false,
  },
  voice_full_prompt: {
    name: 'Voice Full Prompt',
    description: 'Use full system prompt instead of truncated',
    status: 'enabled',
    enabledPercentage: 100,
    killSwitch: false,
  },
  voice_transcript_safety: {
    name: 'Voice Transcript Safety',
    description: 'Enable transcript safety checking',
    status: 'enabled',
    enabledPercentage: 100,
    killSwitch: false,
  },
  voice_calling_overlay: {
    name: 'Voice Calling Overlay',
    description: 'New calling overlay UI',
    status: 'enabled',
    enabledPercentage: 100,
    killSwitch: false,
  },
  tts_audio_15: {
    name: 'TTS Audio 1.5',
    description: 'Enable GPT Audio 1.5 text-to-speech voices',
    status: 'enabled',
    enabledPercentage: 100,
    killSwitch: false,
  },
  chat_unified_view: {
    name: 'Chat Unified View',
    description: 'Unified conversation view across character types',
    status: 'enabled',
    enabledPercentage: 100,
    killSwitch: false,
  },
  consent_unified_model: {
    name: 'Consent Unified Model',
    description: 'Unified consent storage model',
    status: 'enabled',
    enabledPercentage: 100,
    killSwitch: false,
  },
};
