import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

async function main() {
  console.log("Seeding tier definitions with per-feature models (ADR 0073)...");

  // Trial Tier - Cost-effective gpt-4o-mini for all features
  const trial = await prisma.tierDefinition.upsert({
    where: { code: "trial" },
    update: {
      // Per-feature models (ADR 0073) - all gpt-4o-mini for cost
      chatModel: "gpt-4o-mini",
      realtimeModel: "gpt-realtime-mini",
      pdfModel: "gpt-4o-mini",
      mindmapModel: "gpt-4o-mini",
      quizModel: "gpt-4o-mini",
      flashcardsModel: "gpt-4o-mini",
      summaryModel: "gpt-4o-mini",
      formulaModel: "gpt-4o-mini",
      chartModel: "gpt-4o-mini",
      homeworkModel: "gpt-4o-mini",
      webcamModel: "gpt-4o-mini",
      demoModel: "gpt-4o-mini",
    },
    create: {
      code: "trial",
      name: "Trial",
      description: "Free trial tier with limited access",
      chatLimitDaily: 10,
      voiceMinutesDaily: 5,
      toolsLimitDaily: 10,
      docsLimitTotal: 1,
      // Per-feature models (ADR 0073) - cost-effective for trial
      chatModel: "gpt-4o-mini",
      realtimeModel: "gpt-realtime-mini",
      pdfModel: "gpt-4o-mini",
      mindmapModel: "gpt-4o-mini",
      quizModel: "gpt-4o-mini",
      flashcardsModel: "gpt-4o-mini",
      summaryModel: "gpt-4o-mini",
      formulaModel: "gpt-4o-mini",
      chartModel: "gpt-4o-mini",
      homeworkModel: "gpt-4o-mini",
      webcamModel: "gpt-4o-mini",
      demoModel: "gpt-4o-mini",
      features: {
        chat: true,
        voice: true,
        flashcards: true,
        quizzes: true,
        mindMaps: true,
        tools: ["pdf", "chat"],
        maestriLimit: 3,
        coachesAvailable: ["melissa"],
        buddiesAvailable: ["mario"],
      },
      availableMaestri: ["leonardo-art", "galileo-physics", "curie-chemistry"],
      availableCoaches: ["melissa"],
      availableBuddies: ["mario"],
      availableTools: ["pdf", "chat"],
      monthlyPriceEur: null,
      sortOrder: 1,
      isActive: true,
    },
  });

  // Base Tier - Education-optimized models for registered users
  const base = await prisma.tierDefinition.upsert({
    where: { code: "base" },
    update: {
      // Per-feature models (ADR 0073) - education-optimized mix
      chatModel: "gpt-5.2-edu",
      realtimeModel: "gpt-realtime",
      pdfModel: "gpt-5-mini",
      mindmapModel: "gpt-5-mini",
      quizModel: "gpt-5.2-edu",
      flashcardsModel: "gpt-5-mini",
      summaryModel: "gpt-5-mini",
      formulaModel: "gpt-5.2-edu",
      chartModel: "gpt-5-mini",
      homeworkModel: "gpt-5.2-edu",
      webcamModel: "gpt-5.2-edu",
      demoModel: "gpt-4o-mini",
    },
    create: {
      code: "base",
      name: "Base",
      description: "Freemium tier with access to all maestri",
      chatLimitDaily: 50,
      voiceMinutesDaily: 30,
      toolsLimitDaily: 30,
      docsLimitTotal: 5,
      // Per-feature models (ADR 0073) - education-optimized for registered
      chatModel: "gpt-5.2-edu",
      realtimeModel: "gpt-realtime",
      pdfModel: "gpt-5-mini",
      mindmapModel: "gpt-5-mini",
      quizModel: "gpt-5.2-edu",
      flashcardsModel: "gpt-5-mini",
      summaryModel: "gpt-5-mini",
      formulaModel: "gpt-5.2-edu",
      chartModel: "gpt-5-mini",
      homeworkModel: "gpt-5.2-edu",
      webcamModel: "gpt-5.2-edu",
      demoModel: "gpt-4o-mini",
      features: {
        chat: true,
        voice: true,
        flashcards: true,
        quizzes: true,
        mindMaps: true,
        tools: ["pdf", "chat", "flashcards", "mindmap"],
        maestriLimit: 20,
        coachesAvailable: ["melissa", "roberto", "chiara"],
        buddiesAvailable: ["mario", "noemi", "enea"],
        parentDashboard: true,
      },
      availableMaestri: [
        "leonardo-art",
        "galileo-physics",
        "curie-chemistry",
        "cicerone-civic-education",
        "lovelace-computer-science",
        "smith-economics",
        "shakespeare-english",
        "humboldt-geography",
        "erodoto-history",
        "manzoni-italian",
        "euclide-mathematics",
        "mozart-music",
        "socrate-philosophy",
        "ippocrate-health",
        "feynman-physics",
        "darwin-biology",
        "chris-physical-education",
        "omero-storytelling",
        "alex-pina-spanish",
        "simone-sport",
      ],
      availableCoaches: ["melissa", "roberto", "chiara", "andrea", "favij"],
      availableBuddies: ["mario", "noemi", "enea", "bruno", "sofia"],
      availableTools: [
        "pdf",
        "chat",
        "flashcards",
        "mindmap",
        "quiz",
        "formula",
      ],
      monthlyPriceEur: null,
      sortOrder: 2,
      isActive: true,
    },
  });

  // Pro Tier - Best models for all features
  const pro = await prisma.tierDefinition.upsert({
    where: { code: "pro" },
    update: {
      // Per-feature models (ADR 0073) - best quality for paying users
      chatModel: "gpt-5.2-chat",
      realtimeModel: "gpt-realtime",
      pdfModel: "gpt-5.2-chat",
      mindmapModel: "gpt-5.2-chat",
      quizModel: "gpt-5.2-chat",
      flashcardsModel: "gpt-5.2-chat",
      summaryModel: "gpt-5.2-chat",
      formulaModel: "gpt-5.2-chat",
      chartModel: "gpt-5.2-chat",
      homeworkModel: "gpt-5.2-chat",
      webcamModel: "gpt-5.2-chat",
      demoModel: "gpt-4o-mini",
    },
    create: {
      code: "pro",
      name: "Pro",
      description:
        "Professional tier with unlimited access and priority support",
      chatLimitDaily: 999999,
      voiceMinutesDaily: 999999,
      toolsLimitDaily: 999999,
      docsLimitTotal: 999999,
      // Per-feature models (ADR 0073) - best quality for Pro tier
      chatModel: "gpt-5.2-chat",
      realtimeModel: "gpt-realtime",
      pdfModel: "gpt-5.2-chat",
      mindmapModel: "gpt-5.2-chat",
      quizModel: "gpt-5.2-chat",
      flashcardsModel: "gpt-5.2-chat",
      summaryModel: "gpt-5.2-chat",
      formulaModel: "gpt-5.2-chat",
      chartModel: "gpt-5.2-chat",
      homeworkModel: "gpt-5.2-chat",
      webcamModel: "gpt-5.2-chat",
      demoModel: "gpt-4o-mini",
      features: {
        chat: true,
        voice: true,
        flashcards: true,
        quizzes: true,
        mindMaps: true,
        tools: [
          "pdf",
          "chat",
          "flashcards",
          "mindmap",
          "quiz",
          "formula",
          "webcam",
          "homework",
          "chart",
        ],
        maestriLimit: 22,
        coachesAvailable: [
          "melissa",
          "roberto",
          "chiara",
          "andrea",
          "favij",
          "laura",
        ],
        buddiesAvailable: ["mario", "noemi", "enea", "bruno", "sofia", "marta"],
        parentDashboard: true,
        prioritySupport: true,
        advancedAnalytics: true,
        unlimitedStorage: true,
      },
      availableMaestri: [
        "leonardo-art",
        "galileo-physics",
        "curie-chemistry",
        "cicerone-civic-education",
        "lovelace-computer-science",
        "smith-economics",
        "shakespeare-english",
        "humboldt-geography",
        "erodoto-history",
        "manzoni-italian",
        "euclide-mathematics",
        "mozart-music",
        "socrate-philosophy",
        "ippocrate-health",
        "feynman-physics",
        "darwin-biology",
        "chris-physical-education",
        "omero-storytelling",
        "alex-pina-spanish",
        "simone-sport",
        "cassese-international-law",
        "mascetti-supercazzola",
      ],
      availableCoaches: [
        "melissa",
        "roberto",
        "chiara",
        "andrea",
        "favij",
        "laura",
      ],
      availableBuddies: ["mario", "noemi", "enea", "bruno", "sofia", "marta"],
      availableTools: [
        "pdf",
        "chat",
        "flashcards",
        "mindmap",
        "quiz",
        "formula",
        "webcam",
        "homework",
        "chart",
      ],
      stripePriceId: process.env.STRIPE_PRICE_PRO || undefined,
      monthlyPriceEur: 9.99,
      sortOrder: 3,
      isActive: true,
    },
  });

  console.log("Tier seed completed:", { trial, base, pro });
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
