import type { LucideIcon } from "lucide-react";
import {
  LayoutDashboard,
  Users,
  UserPlus,
  Layers,
  ScrollText,
  Palette,
  Languages,
  BarChart3,
  Activity,
  Shield,
  FileText,
  Settings,
  Monitor,
  Sliders,
  Heart,
  Server,
  TrendingUp,
  CreditCard,
  Key,
  Mail,
  FunnelIcon as Funnel,
  Search,
  UserCheck,
  UserX,
  RefreshCw,
} from "lucide-react";

export interface CommandItem {
  id: string;
  label: string;
  section: "navigation" | "action";
  icon: LucideIcon;
  href?: string;
  action?: string;
  keywords?: string[];
}

export function getCommandItems(t: (key: string) => string): CommandItem[] {
  return [
    // Navigation items
    {
      id: "nav-dashboard",
      label: t("sidebar.dashboard"),
      section: "navigation",
      icon: LayoutDashboard,
      href: "/admin",
      keywords: ["home", "overview"],
    },
    {
      id: "nav-users",
      label: t("sidebar.users"),
      section: "navigation",
      icon: Users,
      href: "/admin/users",
      keywords: ["people", "accounts"],
    },
    {
      id: "nav-invites",
      label: t("betaRequests"),
      section: "navigation",
      icon: UserPlus,
      href: "/admin/invites",
      keywords: ["beta", "requests"],
    },
    {
      id: "nav-tiers",
      label: t("sidebar.tiers"),
      section: "navigation",
      icon: Layers,
      href: "/admin/tiers",
      keywords: ["plans", "pricing"],
    },
    {
      id: "nav-audit",
      label: t("sidebar.auditLog"),
      section: "navigation",
      icon: ScrollText,
      href: "/admin/tiers/audit-log",
      keywords: ["log", "history"],
    },
    {
      id: "nav-characters",
      label: "Characters",
      section: "navigation",
      icon: Palette,
      href: "/admin/characters",
      keywords: ["maestri", "coaches", "buddies"],
    },
    {
      id: "nav-locales",
      label: "Locales",
      section: "navigation",
      icon: Languages,
      href: "/admin/locales",
      keywords: ["i18n", "translations"],
    },
    {
      id: "nav-analytics",
      label: t("sidebar.analytics"),
      section: "navigation",
      icon: BarChart3,
      href: "/admin/analytics",
      keywords: ["stats", "metrics"],
    },
    {
      id: "nav-funnel",
      label: "Funnel",
      section: "navigation",
      icon: Funnel,
      href: "/admin/funnel",
      keywords: ["conversion", "pipeline"],
    },
    {
      id: "nav-limits",
      label: t("sidebar.serviceLimits"),
      section: "navigation",
      icon: Activity,
      href: "/admin/service-limits",
      keywords: ["quota", "usage"],
    },
    {
      id: "nav-safety",
      label: "Safety",
      section: "navigation",
      icon: Shield,
      href: "/admin/safety",
      keywords: ["guardrails", "content"],
    },
    {
      id: "nav-tos",
      label: t("terms"),
      section: "navigation",
      icon: FileText,
      href: "/admin/tos",
      keywords: ["legal", "terms"],
    },
    {
      id: "nav-settings",
      label: t("sidebar.settings"),
      section: "navigation",
      icon: Settings,
      href: "/admin/settings",
      keywords: ["config", "preferences"],
    },
    {
      id: "nav-ops",
      label: "Ops Dashboard",
      section: "navigation",
      icon: Monitor,
      href: "/admin/mission-control/ops-dashboard",
      keywords: ["operations"],
    },
    {
      id: "nav-control",
      label: "Control Panel",
      section: "navigation",
      icon: Sliders,
      href: "/admin/mission-control/control-panel",
    },
    {
      id: "nav-health",
      label: "Health",
      section: "navigation",
      icon: Heart,
      href: "/admin/mission-control/health",
      keywords: ["status", "uptime"],
    },
    {
      id: "nav-infra",
      label: "Infrastructure",
      section: "navigation",
      icon: Server,
      href: "/admin/mission-control/infra",
    },
    {
      id: "nav-kpi",
      label: "Business KPI",
      section: "navigation",
      icon: TrendingUp,
      href: "/admin/mission-control/business-kpi",
    },
    {
      id: "nav-stripe",
      label: "Stripe",
      section: "navigation",
      icon: CreditCard,
      href: "/admin/mission-control/stripe",
      keywords: ["payments", "billing"],
    },
    {
      id: "nav-keyvault",
      label: "Key Vault",
      section: "navigation",
      icon: Key,
      href: "/admin/mission-control/key-vault",
      keywords: ["secrets", "env"],
    },
    {
      id: "nav-email",
      label: "AI Email",
      section: "navigation",
      icon: Mail,
      href: "/admin/mission-control/ai-email",
    },
    // Quick actions
    {
      id: "act-search-user",
      label: "Search user by email",
      section: "action",
      icon: Search,
      action: "searchUser",
      keywords: ["find", "lookup"],
    },
    {
      id: "act-approve-invites",
      label: "Approve pending invites",
      section: "action",
      icon: UserCheck,
      action: "approveInvites",
      keywords: ["accept", "beta"],
    },
    {
      id: "act-disable-user",
      label: "Disable a user",
      section: "action",
      icon: UserX,
      action: "disableUser",
      keywords: ["ban", "block"],
    },
    {
      id: "act-refresh",
      label: "Refresh admin data",
      section: "action",
      icon: RefreshCw,
      action: "refresh",
      keywords: ["reload", "sync"],
    },
  ];
}
