'use client';

import { useState } from 'react';
import { motion } from 'framer-motion';
import { cn } from '@/lib/utils';
import type { CalculatorData, CalculatorStep } from '@/types';

interface CalculatorRendererProps {
  data: CalculatorData;
  className?: string;
}

export function CalculatorRenderer({
  data,
  className
}: CalculatorRendererProps) {
  const [expandedSteps, setExpandedSteps] = useState(true);

  return (
    <motion.div
      initial={{ opacity: 0, y: 10 }}
      animate={{ opacity: 1, y: 0 }}
      className={cn(
        'rounded-xl border border-slate-200 dark:border-slate-700 overflow-hidden bg-slate-800',
        className
      )}
    >
      {/* Expression and Result */}
      <div className="p-6 space-y-4">
        {/* Expression */}
        <div className="text-slate-400 text-sm font-mono">
          {data.expression}
        </div>

        {/* Result */}
        <div className="flex items-center justify-center min-h-[60px]">
          <div className="text-4xl font-bold text-emerald-400">
            {typeof data.result === 'number'
              ? data.result.toLocaleString('it-IT', { maximumFractionDigits: 10 })
              : String(data.result)
            }
          </div>
        </div>

        {/* LaTeX formula if available */}
        {data.latex && (
          <div className="text-slate-300 text-center text-sm font-mono">
            {data.latex}
          </div>
        )}
      </div>

      {/* Step-by-step breakdown */}
      {data.steps && data.steps.length > 0 && (
        <div className="border-t border-slate-700">
          <button
            type="button"
            onClick={() => setExpandedSteps(!expandedSteps)}
            className="w-full px-4 py-3 flex items-center justify-between bg-slate-800/50 hover:bg-slate-800/70 transition-colors"
            aria-expanded={expandedSteps}
            aria-label={expandedSteps ? 'Nascondi passaggi di calcolo' : 'Mostra passaggi di calcolo'}
          >
            <span className="text-sm font-medium text-slate-300">
              Passaggi di calcolo ({data.steps.length})
            </span>
            <svg
              className={cn(
                'w-5 h-5 text-slate-400 transition-transform',
                expandedSteps ? 'rotate-180' : ''
              )}
              fill="none"
              viewBox="0 0 24 24"
              stroke="currentColor"
            >
              <path
                strokeLinecap="round"
                strokeLinejoin="round"
                strokeWidth={2}
                d="M19 9l-7 7-7-7"
              />
            </svg>
          </button>

          {expandedSteps && (
            <div className="px-4 py-3 space-y-3">
              {data.steps.map((step) => (
                <CalculatorStepItem key={step.stepNumber} step={step} />
              ))}
            </div>
          )}
        </div>
      )}

      {/* Description */}
      {data.description && (
        <div className="px-4 py-3 border-t border-slate-700 bg-slate-800/50">
          <p className="text-sm text-slate-400">{data.description}</p>
        </div>
      )}
    </motion.div>
  );
}

// Individual step component
interface CalculatorStepItemProps {
  step: CalculatorStep;
}

function CalculatorStepItem({ step }: CalculatorStepItemProps) {
  return (
    <div className="p-3 rounded-lg bg-slate-900/50 border border-slate-700">
      {/* Step number and description */}
      <div className="flex items-start gap-3 mb-2">
        <div className="flex-shrink-0 w-6 h-6 rounded-full bg-blue-500/20 text-blue-400 flex items-center justify-center text-xs font-bold">
          {step.stepNumber}
        </div>
        <div className="flex-1">
          <p className="text-sm text-slate-300">{step.description}</p>
        </div>
      </div>

      {/* Expression */}
      <div className="ml-9 space-y-2">
        <div className="text-sm font-mono text-slate-400">
          {step.expression}
        </div>

        {/* Visual representation (color-coded for dyscalculia) */}
        {/* Note: step.visual is generated by formatNumberColored() which produces controlled HTML
            with only span tags and inline styles. No user input flows into this HTML. */}
        {step.visual && (
          <div
            className="text-sm"
            dangerouslySetInnerHTML={{ __html: step.visual }}
          />
        )}

        {/* Result */}
        <div className="text-base font-semibold text-emerald-400">
          = {typeof step.result === 'number'
            ? step.result.toLocaleString('it-IT', { maximumFractionDigits: 10 })
            : String(step.result)
          }
        </div>
      </div>
    </div>
  );
}

// Note: CalculatorButton component removed - was unused exported code.
// When interactive calculator mode is needed, implement fresh with proper accessibility.
