/**
 * Generated mini-KBs must match their knowledge source (DATA-GOVERNANCE-SOP.md §6.1).
 *
 * The mini-KB is the slice of each knowledge file that gets inlined into the
 * persona prompt, so it — not the knowledge file — is what actually reaches the
 * model. It is committed source generated by scripts/extract-mini-kb.ts, and
 * nothing re-ran the generator when the corpus was sanitised: the dialogue and
 * quotations removed from the knowledge files were still being shipped from
 * mini-kb/. That is finding G-8.
 *
 * A removal is only real once it reaches here.
 */

import { describe, expect, it } from 'vitest';
import * as fs from 'fs';
import * as path from 'path';

import { expectedMiniKBFile, isHandAuthored } from '../../../../../../scripts/extract-mini-kb';

const MAESTRI_DIR = path.join(__dirname, '../../../data/maestri');
const MINI_KB_DIR = path.join(MAESTRI_DIR, 'mini-kb');

const knowledgeFiles = fs
  .readdirSync(MAESTRI_DIR)
  .filter((f) => f.endsWith('-knowledge.ts'))
  .sort();

describe('mini-KB / knowledge base synchronisation', () => {
  it('finds the corpus', () => {
    expect(knowledgeFiles.length).toBeGreaterThanOrEqual(32);
  });

  it('regenerates every generated mini-KB byte-identically', () => {
    const stale: string[] = [];

    for (const file of knowledgeFiles) {
      const slug = file.replace('-knowledge.ts', '');
      const miniKBPath = path.join(MINI_KB_DIR, `${slug}.ts`);

      // Hand-authored mini-KBs are not derived from the knowledge file and the
      // extractor refuses to overwrite them. They are covered by review, not here.
      if (!fs.existsSync(miniKBPath) || isHandAuthored(miniKBPath)) continue;

      const expected = expectedMiniKBFile(path.join(MAESTRI_DIR, file));
      if (expected === null) continue;

      if (fs.readFileSync(miniKBPath, 'utf-8') !== expected) stale.push(slug);
    }

    expect(
      stale,
      `mini-kb/ is out of date with the knowledge files for: ${stale.join(', ')}. ` +
        `Run "npm run kb:extract". Until you do, the old text is what the persona ` +
        `prompt sends to the model, whatever the knowledge file now says.`,
    ).toEqual([]);
  });

  it('leaves hand-authored mini-KBs out of generation', () => {
    const handAuthored = fs
      .readdirSync(MINI_KB_DIR)
      .filter((f) => f.endsWith('.ts'))
      .filter((f) => isHandAuthored(path.join(MINI_KB_DIR, f)))
      .map((f) => f.replace('.ts', ''))
      .sort();

    // Explicit roster: adding a hand-authored mini-KB is a deliberate act, and
    // silently dropping one out of the generator's reach should not be.
    expect(handAuthored).toEqual(['austen', 'kahlo', 'loto', 'nightingale', 'noether', 'turing']);
  });
});
