/**
 * Extract Mini-KB from Maestri Knowledge Files
 *
 * Separates each *-knowledge.ts into:
 * - mini-kb (identity: bio, style, quotes — max 50 lines)
 * - didactic content (bulk for RAG seeding)
 *
 * Usage:
 *   npx tsx scripts/extract-mini-kb.ts           # generate files
 *   npx tsx scripts/extract-mini-kb.ts --dry-run  # preview only
 */

import * as fs from 'fs';
import * as path from 'path';

const MAESTRI_DIR = path.join(__dirname, '../src/data/maestri');
const MINI_KB_DIR = path.join(MAESTRI_DIR, 'mini-kb');
const DIDACTIC_DIR = path.join(__dirname, '../.tmp/didactic-content');
const MAX_MINI_KB_LINES = 50;

const IDENTITY_PATTERNS = [
  /^biograph/i,
  /^biografia/i,
  /^identity/i,
  /^communication\s+style/i,
  /^stile\s+comunicativo/i,
  /^famous\s+quote/i,
  /^citazioni\s+famose/i,
  /^citazioni\s+bilingue/i,
  /^citazioni\s+iconiche/i,
  /^famous\s+anecdote/i,
  /^aneddoti/i,
  /^pedagogical\s+principle/i,
  /^slang\s+spagnolo/i,
  /^ted\s+talk\s+principle/i,
  /^famous\s+advice/i,
  /^presentation\s+design/i,
  /^i\s+cinque\s+amici/i,
  /^la\s+supercazzola/i,
  /^relazioni\s+chiave/i,
  /^il\s+processo/i,
  /^il\s+metodo\s+maieutico/i,
  /^the\s+hippocratic\s+oath/i,
  /^visionary\s+ideas/i,
  /^palmares/i,
  /^palmarès/i,
  /^overcoming\s+obstacles/i,
  /^the\s+feynman\s+technique/i,
  /^the\s+galileo\s+affair/i,
  /^temi\s+fondamentali/i,
  /^temi\s+universali/i,
  /^connessioni\s+moderne/i,
  /^override\s+per\s+studenti/i,
];

interface Section {
  heading: string;
  content: string;
  isIdentity: boolean;
}

function isIdentitySection(heading: string): boolean {
  const cleaned = heading.replace(/^#+\s*/, '').trim();
  return IDENTITY_PATTERNS.some((p) => p.test(cleaned));
}

function parseSections(markdown: string): Section[] {
  const lines = markdown.split('\n');
  const sections: Section[] = [];
  let currentHeading = '';
  let currentLines: string[] = [];

  for (const line of lines) {
    if (/^##\s+/.test(line)) {
      if (currentHeading || currentLines.length > 0) {
        sections.push({
          heading: currentHeading,
          content: currentLines.join('\n').trim(),
          isIdentity: isIdentitySection(currentHeading),
        });
      }
      currentHeading = line;
      currentLines = [];
    } else {
      currentLines.push(line);
    }
  }

  if (currentHeading || currentLines.length > 0) {
    sections.push({
      heading: currentHeading,
      content: currentLines.join('\n').trim(),
      isIdentity: isIdentitySection(currentHeading),
    });
  }

  return sections;
}

function extractKnowledgeContent(filePath: string): string | null {
  const raw = fs.readFileSync(filePath, 'utf-8');
  const match = raw.match(/export\s+const\s+\w+\s*=\s*`([\s\S]*?)`;/);
  return match ? match[1].trim() : null;
}

function extractConstName(filePath: string): string | null {
  const raw = fs.readFileSync(filePath, 'utf-8');
  const match = raw.match(/export\s+const\s+(\w+)\s*=/);
  return match ? match[1] : null;
}

function getMaestroSlug(filename: string): string {
  return filename.replace(/-knowledge\.ts$/, '');
}

function toConstName(slug: string): string {
  return slug.toUpperCase().replace(/-/g, '_');
}

function buildMiniKB(sections: Section[]): string {
  const identity = sections.filter((s) => s.isIdentity);
  const parts: string[] = [];
  for (const s of identity) {
    if (s.heading) parts.push(s.heading);
    if (s.content) parts.push(s.content);
    parts.push('');
  }
  let result = parts.join('\n').trim();
  const lines = result.split('\n');
  if (lines.length > MAX_MINI_KB_LINES) {
    result = lines.slice(0, MAX_MINI_KB_LINES).join('\n').trim();
  }
  return result;
}

function buildDidactic(sections: Section[]): string {
  const didactic = sections.filter((s) => !s.isIdentity && s.heading);
  const parts: string[] = [];
  for (const s of didactic) {
    if (s.heading) parts.push(s.heading);
    if (s.content) parts.push(s.content);
    parts.push('');
  }
  return parts.join('\n').trim();
}

function generateMiniKBFile(slug: string, content: string): string {
  const constName = `${toConstName(slug)}_MINI_KB`;
  return `/**
 * ${slug} — Mini Knowledge Base (identity + style)
 * Auto-generated by scripts/extract-mini-kb.ts
 */

export const ${constName} = \`
${content}
\`;
`;
}

function generateDidacticFile(slug: string, constName: string, content: string): string {
  return `/**
 * ${slug} — Didactic Content (for RAG seeding)
 * Auto-generated by scripts/extract-mini-kb.ts
 */

export const maestroId = '${slug}';
export const subject = '${slug}';
export const content = \`
${content}
\`;
`;
}

function main() {
  const dryRun = process.argv.includes('--dry-run');

  const knowledgeFiles = fs
    .readdirSync(MAESTRI_DIR)
    .filter((f) => f.endsWith('-knowledge.ts'))
    .sort();

  if (!dryRun) {
    fs.mkdirSync(MINI_KB_DIR, { recursive: true });
    fs.mkdirSync(DIDACTIC_DIR, { recursive: true });
  }

  let generated = 0;

  for (const file of knowledgeFiles) {
    const filePath = path.join(MAESTRI_DIR, file);
    const slug = getMaestroSlug(file);
    const originalConst = extractConstName(filePath);
    const markdown = extractKnowledgeContent(filePath);

    if (!markdown) {
      console.warn(`⚠️  Could not parse: ${file}`);
      continue;
    }

    const sections = parseSections(markdown);
    const miniKB = buildMiniKB(sections);
    const didactic = buildDidactic(sections);

    const miniKBLines = miniKB.split('\n').length;
    const didacticLines = didactic.split('\n').length;
    const identityCount = sections.filter((s) => s.isIdentity).length;
    const didacticCount = sections.filter((s) => !s.isIdentity && s.heading).length;

    console.log(
      `${slug}: ${identityCount} identity (${miniKBLines} lines) + ${didacticCount} didactic (${didacticLines} lines)`,
    );

    if (!dryRun) {
      const miniKBPath = path.join(MINI_KB_DIR, `${slug}.ts`);
      fs.writeFileSync(miniKBPath, generateMiniKBFile(slug, miniKB));

      const didacticPath = path.join(DIDACTIC_DIR, `${slug}.ts`);
      fs.writeFileSync(didacticPath, generateDidacticFile(slug, originalConst || '', didactic));
    }

    generated++;
  }

  console.log(
    `\n${dryRun ? '[DRY RUN] ' : ''}${generated}/${knowledgeFiles.length} maestri processed`,
  );
  if (!dryRun) {
    console.log(`Mini-KB files: ${MINI_KB_DIR}`);
    console.log(`Didactic files: ${DIDACTIC_DIR}`);
  }
}

main();
