/**
 * Extract Mini-KB from Maestri Knowledge Files
 *
 * Separates each *-knowledge.ts into:
 * - mini-kb (identity: bio, style, quotes — max 50 lines)
 * - didactic content (bulk for RAG seeding)
 *
 * Usage:
 *   npm run kb:extract                 # regenerate mini-kb + didactic content
 *   npm run script -- scripts/extract-mini-kb.ts --dry-run       # preview only
 *   npm run script -- scripts/extract-mini-kb.ts --didactic-only # leave committed mini-kb untouched
 *
 * `--didactic-only` is what the seeding pipeline uses: the mini-kb files are
 * committed source imported by the maestro definitions, so a seed run must not
 * silently rewrite them.
 */

import * as fs from 'fs';
import * as path from 'path';

const MAESTRI_DIR = path.join(__dirname, '../apps/web/src/data/maestri');
const MINI_KB_DIR = path.join(MAESTRI_DIR, 'mini-kb');
const DIDACTIC_DIR = path.join(__dirname, '../.tmp/didactic-content');
const MAX_MINI_KB_LINES = 50;
const GENERATED_MARKER = 'Auto-generated by scripts/extract-mini-kb.ts';

/** Heading the identity overflow is filed under in the didactic corpus. */
const OVERFLOW_HEADING = '## Approfondimento su identita e stile';

const IDENTITY_PATTERNS = [
  /^biograph/i,
  /^biografia/i,
  /^identity/i,
  /^communication\s+style/i,
  /^stile\s+comunicativo/i,
  /^famous\s+quote/i,
  /^citazioni\s+famose/i,
  /^citazioni\s+bilingue/i,
  /^citazioni\s+iconiche/i,
  /^famous\s+anecdote/i,
  /^aneddoti/i,
  /^pedagogical\s+principle/i,
  /^slang\s+spagnolo/i,
  /^ted\s+talk\s+principle/i,
  /^famous\s+advice/i,
  /^principi\s+guida/i,
  /^presentation\s+design/i,
  /^i\s+cinque\s+amici/i,
  /^la\s+supercazzola/i,
  /^relazioni\s+chiave/i,
  /^il\s+processo/i,
  /^il\s+metodo\s+maieutico/i,
  /^the\s+hippocratic\s+oath/i,
  /^visionary\s+ideas/i,
  /^palmares/i,
  /^palmarès/i,
  /^overcoming\s+obstacles/i,
  /^the\s+feynman\s+technique/i,
  /^the\s+galileo\s+affair/i,
  /^temi\s+fondamentali/i,
  /^temi\s+universali/i,
  /^connessioni\s+moderne/i,
  /^override\s+per\s+studenti/i,
];

interface Section {
  heading: string;
  content: string;
  isIdentity: boolean;
}

function isIdentitySection(heading: string): boolean {
  const cleaned = heading.replace(/^#+\s*/, '').trim();
  return IDENTITY_PATTERNS.some((p) => p.test(cleaned));
}

function parseSections(markdown: string): Section[] {
  const lines = markdown.split('\n');
  const sections: Section[] = [];
  let currentHeading = '';
  let currentLines: string[] = [];

  for (const line of lines) {
    if (/^##\s+/.test(line)) {
      if (currentHeading || currentLines.length > 0) {
        sections.push({
          heading: currentHeading,
          content: currentLines.join('\n').trim(),
          isIdentity: isIdentitySection(currentHeading),
        });
      }
      currentHeading = line;
      currentLines = [];
    } else {
      currentLines.push(line);
    }
  }

  if (currentHeading || currentLines.length > 0) {
    sections.push({
      heading: currentHeading,
      content: currentLines.join('\n').trim(),
      isIdentity: isIdentitySection(currentHeading),
    });
  }

  return sections;
}

function extractKnowledgeContent(filePath: string): string | null {
  const raw = fs.readFileSync(filePath, 'utf-8');
  const match = raw.match(/export\s+const\s+\w+\s*=\s*`([\s\S]*?)`;/);
  return match ? match[1].trim() : null;
}

function extractConstName(filePath: string): string | null {
  const raw = fs.readFileSync(filePath, 'utf-8');
  const match = raw.match(/export\s+const\s+(\w+)\s*=/);
  return match ? match[1] : null;
}

function getMaestroSlug(filename: string): string {
  return filename.replace(/-knowledge\.ts$/, '');
}

function toConstName(slug: string): string {
  return slug.toUpperCase().replace(/-/g, '_');
}

/**
 * The identity sections, capped: the mini-KB is inlined into every persona
 * prompt, so it cannot grow without bound.
 *
 * Whatever the cap cuts is returned rather than dropped. Identity sections
 * never reach the didactic path, so before this the overflow was in neither
 * artefact and simply stopped existing at runtime — 305 lines across 17 of the
 * 32 Maestri, silently.
 */
function buildMiniKB(sections: Section[]): { content: string; overflow: string } {
  const identity = sections.filter((s) => s.isIdentity);
  const parts: string[] = [];
  for (const s of identity) {
    if (s.heading) parts.push(s.heading);
    if (s.content) parts.push(s.content);
    parts.push('');
  }
  const lines = parts.join('\n').trim().split('\n');

  if (lines.length <= MAX_MINI_KB_LINES) {
    return { content: lines.join('\n').trim(), overflow: '' };
  }

  return {
    content: lines.slice(0, MAX_MINI_KB_LINES).join('\n').trim(),
    overflow: lines.slice(MAX_MINI_KB_LINES).join('\n').trim(),
  };
}

/**
 * Everything the prompt does not carry, for RAG seeding: the non-identity
 * sections, plus any identity content the cap pushed out of the mini-KB.
 *
 * A section with no heading is the text before the first `##`. It used to be
 * filtered out here, which was a second silent drain — unexercised today, since
 * every file opens with a heading, but a trap for the next author.
 */
function buildDidactic(sections: Section[], overflow = ''): string {
  const didactic = sections.filter((s) => !s.isIdentity);
  const parts: string[] = [];
  for (const s of didactic) {
    if (s.heading) parts.push(s.heading);
    if (s.content) parts.push(s.content);
    parts.push('');
  }

  if (overflow) {
    parts.push(OVERFLOW_HEADING);
    parts.push(overflow);
    parts.push('');
  }

  return parts.join('\n').trim();
}

/**
 * A few mini-KBs are written by hand rather than extracted: they carry a
 * first-person voice that no section-picking heuristic can produce. They are
 * recognised by the absence of the generator's marker in their header, and are
 * left alone — overwriting them silently discards authored work.
 */
function isHandAuthored(miniKBPath: string): boolean {
  if (!fs.existsSync(miniKBPath)) return false;
  const header = fs.readFileSync(miniKBPath, 'utf-8').split('\n').slice(0, 12).join('\n');
  return !header.includes(GENERATED_MARKER);
}

/**
 * For a hand-authored mini-KB the generated one is computed and thrown away, so
 * the cap is not what strands identity content — the discard is. Whatever the
 * human rewrite happens not to carry has to reach RAG instead.
 *
 * Compared line by line against the real committed file rather than assumed:
 * the rewrite is in a different voice, so it covers some source lines verbatim
 * and paraphrases others, and only the file itself knows which.
 */
function identityNotCarriedBy(sections: Section[], realMiniKB: string): string {
  return sections
    .filter((s) => s.isIdentity)
    .flatMap((s) => [s.heading, s.content].filter(Boolean).join('\n').split('\n'))
    .filter((line) => line.trim() && !realMiniKB.includes(line.trim()))
    .join('\n')
    .trim();
}

/**
 * What the two runtime paths actually carry for a knowledge file: the mini-KB
 * the persona prompt inlines, and the didactic text the RAG seeding embeds.
 *
 * This reads the committed mini-KB for hand-authored Maestri instead of the
 * generated one, because that is the file that ships. Recomputing it here was
 * how the first version of the guard came to pass while Austen's identity facts
 * were reachable from nowhere: the test and production disagreed about which
 * artefact was real. Both now come through this one function.
 */
export function runtimeArtefacts(knowledgeFilePath: string): {
  source: string;
  miniKB: string;
  didactic: string;
  handAuthored: boolean;
} | null {
  const markdown = extractKnowledgeContent(knowledgeFilePath);
  if (!markdown) return null;

  const slug = getMaestroSlug(path.basename(knowledgeFilePath));
  const miniKBPath = path.join(MINI_KB_DIR, `${slug}.ts`);
  const sections = parseSections(markdown);
  const built = buildMiniKB(sections);
  const handAuthored = isHandAuthored(miniKBPath);

  const miniKB = handAuthored ? fs.readFileSync(miniKBPath, 'utf-8') : built.content;
  const overflow = handAuthored ? identityNotCarriedBy(sections, miniKB) : built.overflow;

  return { source: markdown, miniKB, didactic: buildDidactic(sections, overflow), handAuthored };
}

function generateMiniKBFile(slug: string, content: string): string {
  const constName = `${toConstName(slug)}_MINI_KB`;
  return `/**
 * ${slug} — Mini Knowledge Base (identity + style)
 * Auto-generated by scripts/extract-mini-kb.ts
 */

export const ${constName} = \`
${content}
\`;
`;
}

function generateDidacticFile(slug: string, constName: string, content: string): string {
  return `/**
 * ${slug} — Didactic Content (for RAG seeding)
 * Auto-generated by scripts/extract-mini-kb.ts
 */

export const maestroId = '${slug}';
export const subject = '${slug}';
export const content = \`
${content}
\`;
`;
}

function main() {
  const dryRun = process.argv.includes('--dry-run');
  const didacticOnly = process.argv.includes('--didactic-only');

  if (!fs.existsSync(MAESTRI_DIR)) {
    console.error(`❌ Maestri directory not found: ${MAESTRI_DIR}`);
    process.exit(1);
  }

  const knowledgeFiles = fs
    .readdirSync(MAESTRI_DIR)
    .filter((f) => f.endsWith('-knowledge.ts'))
    .sort();

  if (knowledgeFiles.length === 0) {
    console.error(`❌ No *-knowledge.ts files in ${MAESTRI_DIR}`);
    process.exit(1);
  }

  if (!dryRun) {
    if (!didacticOnly) fs.mkdirSync(MINI_KB_DIR, { recursive: true });
    fs.mkdirSync(DIDACTIC_DIR, { recursive: true });
  }

  let generated = 0;
  const skippedHandAuthored: string[] = [];

  for (const file of knowledgeFiles) {
    const filePath = path.join(MAESTRI_DIR, file);
    const slug = getMaestroSlug(file);
    const originalConst = extractConstName(filePath);
    const markdown = extractKnowledgeContent(filePath);

    if (!markdown) {
      console.warn(`⚠️  Could not parse: ${file}`);
      continue;
    }

    const sections = parseSections(markdown);
    const { content: miniKB, overflow: capOverflow } = buildMiniKB(sections);
    const miniKBPath = path.join(MINI_KB_DIR, `${slug}.ts`);
    const handAuthored = isHandAuthored(miniKBPath);
    const overflow = handAuthored
      ? identityNotCarriedBy(sections, fs.readFileSync(miniKBPath, 'utf-8'))
      : capOverflow;
    const didactic = buildDidactic(sections, overflow);

    const miniKBLines = miniKB.split('\n').length;
    const didacticLines = didactic.split('\n').length;
    const identityCount = sections.filter((s) => s.isIdentity).length;
    const didacticCount = sections.filter((s) => !s.isIdentity && s.heading).length;
    const overflowNote = overflow
      ? ` + ${overflow.split('\n').length} overflow → RAG${handAuthored ? ' (hand-authored)' : ''}`
      : '';

    console.log(
      `${slug}: ${identityCount} identity (${miniKBLines} lines) + ${didacticCount} didactic (${didacticLines} lines)${overflowNote}`,
    );

    if (!dryRun) {
      if (!didacticOnly) {
        if (handAuthored) {
          skippedHandAuthored.push(slug);
        } else {
          fs.writeFileSync(miniKBPath, generateMiniKBFile(slug, miniKB));
        }
      }

      const didacticPath = path.join(DIDACTIC_DIR, `${slug}.ts`);
      fs.writeFileSync(didacticPath, generateDidacticFile(slug, originalConst || '', didactic));
    }

    generated++;
  }

  console.log(
    `\n${dryRun ? '[DRY RUN] ' : ''}${generated}/${knowledgeFiles.length} maestri processed`,
  );
  if (!dryRun) {
    console.log(
      didacticOnly ? 'Mini-KB files: skipped (--didactic-only)' : `Mini-KB files: ${MINI_KB_DIR}`,
    );
    console.log(`Didactic files: ${DIDACTIC_DIR}`);
  }
  if (skippedHandAuthored.length > 0) {
    console.log(
      `Mini-KB left untouched (hand-authored): ${skippedHandAuthored.join(', ')}. ` +
        `Edit those files directly; the extractor will not overwrite them.`,
    );
  }
}

/**
 * Exported so the guard test can recompute what this script would write and
 * compare it against the committed file. A sanitised knowledge file whose
 * mini-KB was never regenerated still reaches the model through the persona
 * prompt; that is what the test catches.
 */
export function expectedMiniKBFile(knowledgeFilePath: string): string | null {
  const markdown = extractKnowledgeContent(knowledgeFilePath);
  if (!markdown) return null;
  const slug = getMaestroSlug(path.basename(knowledgeFilePath));
  return generateMiniKBFile(slug, buildMiniKB(parseSections(markdown)).content);
}

export { isHandAuthored, getMaestroSlug, MAESTRI_DIR, MINI_KB_DIR };

if (require.main === module) {
  main();
}
