#!/usr/bin/env bash
# =============================================================================
# RELEASE EVIDENCE PACK
# Collects build/test/compliance artifacts for audit trail.
# Output: reports/evidence-pack-{version}-{sha}.md
# =============================================================================

set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT_DIR"

RED='\033[0;31m'
GREEN='\033[0;32m'
BLUE='\033[0;34m'
NC='\033[0m'

VERSION=$(node -p "require('./package.json').version" 2>/dev/null || echo "unknown")
SHA=$(git rev-parse --short HEAD 2>/dev/null || echo "unknown")
BRANCH=$(git branch --show-current 2>/dev/null || echo "unknown")
TAG=$(git describe --tags --exact-match 2>/dev/null || echo "untagged")
DATE=$(date -u +"%Y-%m-%dT%H:%M:%SZ")

REPORT_DIR="$ROOT_DIR/reports"
mkdir -p "$REPORT_DIR"
REPORT="$REPORT_DIR/evidence-pack-${VERSION}-${SHA}.md"

echo -e "${BLUE}Generating evidence pack v${VERSION} (${SHA})...${NC}"

# --- Collect evidence ---

lint_result="SKIPPED"
if npm run lint --silent 2>/dev/null; then
  lint_result="PASS"
else
  lint_result="FAIL"
fi

typecheck_result="SKIPPED"
if npx tsc --noEmit 2>/dev/null; then
  typecheck_result="PASS"
else
  typecheck_result="FAIL"
fi

unit_result="SKIPPED"
unit_summary=""
if command -v npx &>/dev/null; then
  unit_output=$(npx vitest run --reporter=verbose 2>&1 || true)
  if echo "$unit_output" | grep -q "Tests.*passed"; then
    unit_result="PASS"
    unit_summary=$(echo "$unit_output" | grep -E "Tests|Test Files" | tail -3)
  elif echo "$unit_output" | grep -q "Tests.*failed"; then
    unit_result="FAIL"
    unit_summary=$(echo "$unit_output" | grep -E "Tests|Test Files" | tail -3)
  fi
fi

sbom_result="SKIPPED"
sbom_path=""
if command -v npx &>/dev/null; then
  sbom_file="$REPORT_DIR/sbom-${VERSION}-${SHA}.json"
  if npx @cyclonedx/cyclonedx-npm --output-file "$sbom_file" 2>/dev/null; then
    sbom_result="GENERATED"
    sbom_path="$sbom_file"
  fi
fi

audit_result="SKIPPED"
audit_summary=""
if command -v npm &>/dev/null; then
  audit_output=$(npm audit --json 2>/dev/null || true)
  audit_vulns=$(echo "$audit_output" | node -p "
    try { const d=JSON.parse(require('fs').readFileSync('/dev/stdin','utf8'));
    const v=d.metadata?.vulnerabilities||{};
    'critical:'+( v.critical||0)+' high:'+(v.high||0)+' moderate:'+(v.moderate||0)+' low:'+(v.low||0)
    } catch(e) { 'parse-error' }
  " 2>/dev/null || echo "unavailable")
  audit_result="DONE"
  audit_summary="$audit_vulns"
fi

changelog_excerpt=""
if [ -f CHANGELOG.md ]; then
  changelog_excerpt=$(sed -n '/^## \[/,/^## \[/p' CHANGELOG.md | head -30)
fi

# --- Write report ---

cat > "$REPORT" << REPORT_EOF
# Release Evidence Pack

| Field       | Value                    |
| ----------- | ------------------------ |
| Version     | ${VERSION}               |
| Git SHA     | ${SHA}                   |
| Branch      | ${BRANCH}                |
| Tag         | ${TAG}                   |
| Generated   | ${DATE}                  |
| Node        | $(node --version 2>/dev/null || echo "N/A") |
| npm         | $(npm --version 2>/dev/null || echo "N/A")  |

## Check Results

| Check      | Result           |
| ---------- | ---------------- |
| Lint       | ${lint_result}   |
| Typecheck  | ${typecheck_result} |
| Unit Tests | ${unit_result}   |
| SBOM       | ${sbom_result}   |
| npm audit  | ${audit_result}  |

## Unit Test Summary

\`\`\`
${unit_summary:-No unit test output available}
\`\`\`

## npm Audit Summary

\`\`\`
${audit_summary:-No audit data available}
\`\`\`

## SBOM

${sbom_path:+Generated at: \`${sbom_path}\`}
${sbom_path:-Not generated (cyclonedx not available)}

## CHANGELOG Excerpt

\`\`\`markdown
${changelog_excerpt:-No CHANGELOG found}
\`\`\`

## Signoff Checklist

- [ ] Code review completed
- [ ] All CI checks passing
- [ ] E2E tests passing (local)
- [ ] Accessibility audit passing
- [ ] Compliance docs reviewed
- [ ] CHANGELOG updated
- [ ] Version bumped
- [ ] Tagged release created

---

*Generated by release-evidence-pack.sh*
REPORT_EOF

echo -e "${GREEN}Evidence pack written to: ${REPORT}${NC}"
echo "  Version: ${VERSION}"
echo "  SHA: ${SHA}"
echo "  Checks: lint=${lint_result} types=${typecheck_result} unit=${unit_result}"
