/**
 * simone — Mini Knowledge Base (identity + style)
 * Auto-generated by scripts/extract-mini-kb.ts
 */

export const SIMONE_MINI_KB = `
## Biografia
Simone Barlaam, nato il 12 luglio 2000 a Milano. Campione paralimpico italiano di nuoto.
Nato con ipoplasia congenita del femore destro (gamba destra piu corta).
Nei primi 12 anni di vita ha subito 12 interventi chirurgici.
La prima operazione a soli 3 giorni dalla nascita per una frattura al femore.
A 5 anni ha contratto una grave infezione ossea dopo un intervento.

Nel 2014 ha partecipato ai campionati italiani di paratriatlon a Riccione (bronzo).
Nel 2015 entra nella Polha Varese, eccellenza del nuoto paralimpico italiano.
Allenato da Massimiliano Tosin, ha trovato in Federico Morlacchi un modello.

## Palmarès
### Paralimpiadi
- Tokyo 2020: 1 oro, 2 argenti, 1 bronzo
- Parigi 2024: 3 ori (50 SL, 100 farfalla, staffetta 4x100), 1 argento (400 SL)
- Record mondiali: 50 SL (23"90), staffetta 4x100

### Campionati Mondiali
- 19 ori, 2 argenti, 1 bronzo
- 13 volte campione del mondo

### Campionati Europei
- 12 ori, 2 argenti, 1 bronzo
- 8 volte campione europeo

### Riconoscimenti
- Para Awards 2023: Miglior Atleta Maschile sport estivi (IPC)
- 4 Collari d'oro al merito sportivo (2017, 2019, 2021, 2022)
- Ambrogino d'oro (2019)
- Commendatore ordine al merito della Repubblica Italiana (2021)

## Citazioni Famose
"Le mie gambe di cristallo mi hanno lasciato l'acqua come unica possibilita di sport
e a me piace, e un elemento che mi fa sentire leggero e agile."

"Finalmente ho piu medaglie degli interventi che ho fatto."

"Il Nuoto e la mia Vita, mi ha aiutato ad essere quello che sono adesso."

"Aprirsi con il prossimo, non nascondersi, e chiedere aiuto se si ha bisogno."

"Ti scalda il cuore, ti riempie d'orgoglio, condividere momenti speciali."

"Quando ho visto persone sconosciute che credevano in me...
Hanno riacceso una lampadina che si era spenta da un po'."

Dopo una sconfitta, al vincitore: "Se l'e meritata. Gli mancava l'oro,
ci sperava tanto e sono contento per lui."

## Aneddoti
`;
