import { describe, expect, it } from 'vitest';

import deSettings from '../../messages/de/settings.json';
import enSettings from '../../messages/en/settings.json';
import esSettings from '../../messages/es/settings.json';
import frSettings from '../../messages/fr/settings.json';
import itSettings from '../../messages/it/settings.json';

const settingsMessages = {
  de: deSettings.settings,
  en: enSettings.settings,
  es: esSettings.settings,
  fr: frSettings.settings,
  it: itSettings.settings,
};

const expectedParentCopy = {
  de: {
    profile: {
      professorFallback: 'Professor',
      dataDeletionRequestConfirm:
        'Sind Sie sicher, dass Sie die Löschung von Daten anfordern möchten?',
      studentLabel: 'Schüler:',
      activityOverview: 'Überblick über Lernaktivitäten',
      updateButton: 'Aktualisieren',
      deleteButton: 'Löschen',
      confidenceNote: 'Zuverlässigkeit {score}%. Mehr Sitzungen verbessern die Beobachtungen.',
      settingsNote: 'Diese Einstellungen gelten nur für die Ansicht des Eltern-Dashboards.',
    },
    retry: 'Erneut versuchen',
    parentChat: {
      askAbout: 'Nach den Fortschritten von {studentName} fragen',
      messagesSaved: 'Nachrichten werden sicher gespeichert',
      observationsStudySessions: 'Beobachtungen basieren auf Lernsitzungen',
      startConversation: 'Gespräch mit {maestroName} starten',
      understood: 'Verstanden, weiter',
    },
    notices: {
      nota1: 'Hinweis:',
      nota: 'Hinweis:',
      disclaimerAi: 'KI-Hinweis:',
      leOsservazioniSonoGenerate:
        'Die Beobachtungen werden von KI erstellt und ersetzen keine professionellen Beurteilungen.',
    },
    composed: {
      confidence: 'Hinweis: Zuverlässigkeit 42%. Mehr Sitzungen verbessern die Beobachtungen.',
      settings: 'Hinweis: Diese Einstellungen gelten nur für die Ansicht des Eltern-Dashboards.',
      disclaimer:
        'KI-Hinweis: Die Beobachtungen werden von KI erstellt und ersetzen keine professionellen Beurteilungen.',
    },
  },
  en: {
    profile: {
      professorFallback: 'Professor',
      dataDeletionRequestConfirm: 'Are you sure you want to request data deletion?',
      studentLabel: 'Student:',
      activityOverview: 'Overview of study activities',
      updateButton: 'Update',
      deleteButton: 'Delete',
      confidenceNote: 'Reliability {score}%. More sessions will improve the observations.',
      settingsNote: 'These settings apply only to the Parent Dashboard view.',
    },
    retry: 'Retry',
    parentChat: {
      askAbout: "Ask about {studentName}'s progress",
      messagesSaved: 'Messages Saved',
      observationsStudySessions: 'Observations Study Sessions',
      startConversation: 'Start conversation with {maestroName}',
      understood: 'Understood',
    },
    notices: {
      nota1: 'Note:',
      nota: 'Note:',
      disclaimerAi: 'AI disclaimer:',
      leOsservazioniSonoGenerate:
        'Observations are generated by AI and do not replace professional evaluations.',
    },
    composed: {
      confidence: 'Note: Reliability 42%. More sessions will improve the observations.',
      settings: 'Note: These settings apply only to the Parent Dashboard view.',
      disclaimer:
        'AI disclaimer: Observations are generated by AI and do not replace professional evaluations.',
    },
  },
  es: {
    profile: {
      professorFallback: 'Profesor',
      dataDeletionRequestConfirm: '¿Está seguro de que desea solicitar la eliminación de datos?',
      studentLabel: 'Estudiante:',
      activityOverview: 'Descripción general de actividades de estudio',
      updateButton: 'Actualizar',
      deleteButton: 'Eliminar',
      confidenceNote: 'Confiabilidad {score}%. Más sesiones mejorarán las observaciones.',
      settingsNote:
        'Estas configuraciones se aplican solo a la vista del Panel de control de padres.',
    },
    retry: 'Reintentar',
    parentChat: {
      askAbout: 'Preguntar sobre el progreso de {studentName}',
      messagesSaved: 'Los mensajes se guardan de forma segura',
      observationsStudySessions: 'Las observaciones se basan en sesiones de estudio',
      startConversation: 'Iniciar conversación con {maestroName}',
      understood: 'Entendido, continuar',
    },
    notices: {
      nota1: 'Nota:',
      nota: 'Nota:',
      disclaimerAi: 'Aviso de IA:',
      leOsservazioniSonoGenerate:
        'Las observaciones son generadas por IA y no sustituyen las evaluaciones profesionales.',
    },
    composed: {
      confidence: 'Nota: Confiabilidad 42%. Más sesiones mejorarán las observaciones.',
      settings:
        'Nota: Estas configuraciones se aplican solo a la vista del Panel de control de padres.',
      disclaimer:
        'Aviso de IA: Las observaciones son generadas por IA y no sustituyen las evaluaciones profesionales.',
    },
  },
  fr: {
    profile: {
      professorFallback: 'Professeur',
      dataDeletionRequestConfirm: 'Êtes-vous sûr de vouloir demander la suppression des données ?',
      studentLabel: 'Élève :',
      activityOverview: "Aperçu des activités d'étude",
      updateButton: 'Mettre à jour',
      deleteButton: 'Supprimer',
      confidenceNote: 'Fiabilité {score}%. Plus de sessions amélioreront les observations.',
      settingsNote:
        "Ces paramètres s'appliquent uniquement à l'affichage du Tableau de bord des parents.",
    },
    retry: 'Réessayer',
    parentChat: {
      askAbout: 'Demander des informations sur les progrès de {studentName}',
      messagesSaved: 'Les messages sont enregistrés de manière sécurisée',
      observationsStudySessions: "Les observations sont basées sur les séances d'étude",
      startConversation: 'Commencer la conversation avec {maestroName}',
      understood: "J'ai compris, continuer",
    },
    notices: {
      nota1: 'Remarque :',
      nota: 'Remarque :',
      disclaimerAi: "Avertissement sur l'IA :",
      leOsservazioniSonoGenerate:
        "Les observations sont générées par l'IA et ne remplacent pas les évaluations professionnelles.",
    },
    composed: {
      confidence: 'Remarque : Fiabilité 42%. Plus de sessions amélioreront les observations.',
      settings:
        "Remarque : Ces paramètres s'appliquent uniquement à l'affichage du Tableau de bord des parents.",
      disclaimer:
        "Avertissement sur l'IA : Les observations sont générées par l'IA et ne remplacent pas les évaluations professionnelles.",
    },
  },
  it: {
    profile: {
      professorFallback: 'Professore',
      dataDeletionRequestConfirm: 'Sei sicuro di voler richiedere la cancellazione dei dati?',
      studentLabel: 'Studente:',
      activityOverview: 'Panoramica delle attività di studio',
      updateButton: 'Aggiorna',
      deleteButton: 'Cancella',
      confidenceNote: 'Affidabilità {score}%. Più sessioni miglioreranno le osservazioni.',
      settingsNote:
        'Queste impostazioni si applicano solo alla visualizzazione del Dashboard Genitori.',
    },
    retry: 'Riprova',
    parentChat: {
      askAbout: 'Chieda informazioni sui progressi di {studentName}',
      messagesSaved: 'I messaggi vengono salvati in modo sicuro',
      observationsStudySessions: 'Le osservazioni si basano sulle sessioni di studio',
      startConversation: 'Inizia la conversazione con {maestroName}',
      understood: 'Ho capito, continua',
    },
    notices: {
      nota1: 'Nota:',
      nota: 'Nota:',
      disclaimerAi: 'Avviso IA:',
      leOsservazioniSonoGenerate:
        "Le osservazioni sono generate dall'IA e non sostituiscono valutazioni professionali.",
    },
    composed: {
      confidence: 'Nota: Affidabilità 42%. Più sessioni miglioreranno le osservazioni.',
      settings:
        'Nota: Queste impostazioni si applicano solo alla visualizzazione del Dashboard Genitori.',
      disclaimer:
        "Avviso IA: Le osservazioni sono generate dall'IA e non sostituiscono valutazioni professionali.",
    },
  },
} as const;

describe('production Parent Area i18n regressions', () => {
  it('uses exact Parent Area copy and composes notices without duplicated prefixes', () => {
    Object.entries(settingsMessages).forEach(([locale, messages]) => {
      const expected = expectedParentCopy[locale as keyof typeof expectedParentCopy];
      expect(messages.profile).toMatchObject({
        ...expected.profile,
        genitori: { retry: expected.retry },
        parentChat: expected.parentChat,
      });
      expect(messages).toMatchObject(expected.notices);
      expect({
        confidence: `${messages.nota1} ${messages.profile.confidenceNote.replace('{score}', '42')}`,
        settings: `${messages.nota} ${messages.profile.settingsNote}`,
        disclaimer: `${messages.disclaimerAi} ${messages.leOsservazioniSonoGenerate}`,
      }).toEqual(expected.composed);
    });
  });
});
