import { describe, expect, it } from 'vitest';

import deAuth from '../../messages/de/auth.json';
import enAuth from '../../messages/en/auth.json';
import esAuth from '../../messages/es/auth.json';
import frAuth from '../../messages/fr/auth.json';
import itAuth from '../../messages/it/auth.json';
import deSettings from '../../messages/de/settings.json';
import enSettings from '../../messages/en/settings.json';
import esSettings from '../../messages/es/settings.json';
import frSettings from '../../messages/fr/settings.json';
import itSettings from '../../messages/it/settings.json';

const localeMessages = {
  de: { auth: deAuth.auth, settings: deSettings.settings },
  en: { auth: enAuth.auth, settings: enSettings.settings },
  es: { auth: esAuth.auth, settings: esSettings.settings },
  fr: { auth: frAuth.auth, settings: frSettings.settings },
  it: { auth: itAuth.auth, settings: itSettings.settings },
};

describe('production i18n regressions', () => {
  it('uses complete invite-request copy in every supported locale', () => {
    const placeholderValues = new Set([
      'Titolo della pagina',
      'Descrizione della pagina',
      'Minimo caratteri',
      'Testo di conferma',
      'Page Title',
      'Page Description',
      'Minimum Characters',
      'Confirmation Text',
    ]);

    Object.entries(localeMessages).forEach(([locale, messages]) => {
      const invite = messages.auth.invite;

      ['pageTitle', 'pageDescription', 'minimumCharacters', 'confirmationText'].forEach((key) => {
        const value = invite[key as keyof typeof invite];
        expect(value, `${locale} auth.invite.${key}`).toBeTypeOf('string');
        expect(placeholderValues, `${locale} auth.invite.${key}`).not.toContain(value);
      });
    });
  });

  it('provides every Parent Area profile label in every supported locale', () => {
    const requiredKeys = [
      'professorFallback',
      'dataDeletionRequestConfirm',
      'studentLabel',
      'activityOverview',
      'updateButton',
      'deleteButton',
      'confidenceNote',
      'settingsNote',
    ] as const;

    Object.entries(localeMessages).forEach(([locale, messages]) => {
      requiredKeys.forEach((key) => {
        expect(messages.settings.profile[key], `${locale} settings.profile.${key}`).toBeTypeOf(
          'string',
        );
      });
      expect(
        messages.settings.leOsservazioniSonoGenerate,
        `${locale} settings.leOsservazioniSonoGenerate`,
      ).toBeTypeOf('string');
    });
  });

  it('does not expose English placeholder labels in the Italian Parent Area', () => {
    expect(itSettings.settings.profile.genitori.retry).toBe('Riprova');
    expect(itSettings.settings.profile.parentChat).toMatchObject({
      askAbout: 'Chieda informazioni sui progressi di {studentName}',
      messagesSaved: 'I messaggi vengono salvati in modo sicuro',
      observationsStudySessions: 'Le osservazioni si basano sulle sessioni di studio',
      understood: 'Ho capito, continua',
    });
  });

  it('composes Parent Area notices without duplicated or mixed-language prefixes', () => {
    const expectedCopy = {
      de: {
        confidence: 'Hinweis: Zuverlässigkeit 42%. Mehr Sitzungen verbessern die Beobachtungen.',
        settings: 'Hinweis: Diese Einstellungen gelten nur für die Ansicht des Eltern-Dashboards.',
        disclaimer:
          'KI-Hinweis: Die Beobachtungen werden von KI erstellt und ersetzen keine professionellen Beurteilungen.',
      },
      en: {
        confidence: 'Note: Reliability 42%. More sessions will improve the observations.',
        settings: 'Note: These settings apply only to the Parent Dashboard view.',
        disclaimer:
          'AI disclaimer: Observations are generated by AI and do not replace professional evaluations.',
      },
      es: {
        confidence: 'Nota: Confiabilidad 42%. Más sesiones mejorarán las observaciones.',
        settings:
          'Nota: Estas configuraciones se aplican solo a la vista del Panel de control de padres.',
        disclaimer:
          'Aviso de IA: Las observaciones son generadas por IA y no sustituyen las evaluaciones profesionales.',
      },
      fr: {
        confidence: 'Remarque : Fiabilité 42%. Plus de sessions amélioreront les observations.',
        settings:
          "Remarque : Ces paramètres s'appliquent uniquement à l'affichage du Tableau de bord des parents.",
        disclaimer:
          "Avertissement sur l'IA : Les observations sont générées par l'IA et ne remplacent pas les évaluations professionnelles.",
      },
      it: {
        confidence: 'Nota: Affidabilità 42%. Più sessioni miglioreranno le osservazioni.',
        settings:
          'Nota: Queste impostazioni si applicano solo alla visualizzazione del Dashboard Genitori.',
        disclaimer:
          "Avviso IA: Le osservazioni sono generate dall'IA e non sostituiscono valutazioni professionali.",
      },
    };

    Object.entries(localeMessages).forEach(([locale, messages]) => {
      const profile = messages.settings.profile;
      const composed = {
        confidence: `${messages.settings.nota1} ${profile.confidenceNote.replace('{score}', '42')}`,
        settings: `${messages.settings.nota} ${profile.settingsNote}`,
        disclaimer: `${messages.settings.disclaimerAi} ${messages.settings.leOsservazioniSonoGenerate}`,
      };

      expect(composed).toEqual(expectedCopy[locale as keyof typeof expectedCopy]);
    });
  });
});
