/**
 * Locale-resolved labels baked into generated PDFs.
 *
 * The PDF is rendered server-side with @react-pdf/renderer's `renderToBuffer`,
 * which runs outside any React/next-intl provider. Calling `useTranslations`
 * there throws, so the document text must be supplied as plain strings resolved
 * from the caller's locale instead.
 */

export interface PDFLabels {
  /** Prefix for the estimated reading time line. */
  readingTimeEstimate: string;
  /** Unit word appended to the reading time value. */
  minutes: string;
  /** Footer attribution shown next to the profile name. */
  generatedBy: string;
  /** Word before the current page number in the footer. */
  page: string;
  /** Word between the current page and total page count. */
  of: string;
  /** Label above an image's alternative-text description. */
  imageDescription: string;
}

const IT: PDFLabels = {
  readingTimeEstimate: 'Tempo di lettura stimato:',
  minutes: 'minuti',
  generatedBy: 'Generato da MirrorBuddy',
  page: 'Pagina',
  of: 'di',
  imageDescription: 'Descrizione immagine:',
};

const EN: PDFLabels = {
  readingTimeEstimate: 'Estimated reading time:',
  minutes: 'minutes',
  generatedBy: 'Generated by MirrorBuddy',
  page: 'Page',
  of: 'of',
  imageDescription: 'Image description:',
};

const FR: PDFLabels = {
  readingTimeEstimate: 'Temps de lecture estimé :',
  minutes: 'minutes',
  generatedBy: 'Généré par MirrorBuddy',
  page: 'Page',
  of: 'sur',
  imageDescription: "Description de l'image :",
};

const DE: PDFLabels = {
  readingTimeEstimate: 'Geschätzte Lesezeit:',
  minutes: 'Minuten',
  generatedBy: 'Erstellt von MirrorBuddy',
  page: 'Seite',
  of: 'von',
  imageDescription: 'Bildbeschreibung:',
};

const ES: PDFLabels = {
  readingTimeEstimate: 'Tiempo de lectura estimado:',
  minutes: 'minutos',
  generatedBy: 'Generado por MirrorBuddy',
  page: 'Página',
  of: 'de',
  imageDescription: 'Descripción de la imagen:',
};

const LABELS_BY_LOCALE: Record<string, PDFLabels> = {
  it: IT,
  en: EN,
  fr: FR,
  de: DE,
  es: ES,
};

/** Italian is the product's default locale, so it is the fallback label set. */
export const DEFAULT_PDF_LABELS: PDFLabels = IT;

/**
 * Resolve the PDF label set for a locale, falling back to Italian for unknown
 * or missing values.
 */
export function getPdfLabels(locale?: string | null): PDFLabels {
  if (!locale) return DEFAULT_PDF_LABELS;
  return LABELS_BY_LOCALE[locale] ?? DEFAULT_PDF_LABELS;
}
